site_name: Pushkin Documentation

site_url: http://pushkin.io

repo_url: https://github.com/Nordeus/pushkin

site_description: Pushkin is a free open source tool for sending push notifications.
site_author: Nordeus

dev_addr: '0.0.0.0:8000'

theme: readthedocs

pages:
- Home: index.md
- Setup certificates: certificates.md
- Measuring results: measuring.md
- Roadmap: roadmap.md

copyright: Â© 2016 <a href="http://www.nordeus.com" target="_blank">Nordeus</a>
